# Test against the latest version of this Node.js version
environment:
  nodejs_version: "6"
  
init:
  - sh: |
      echo 'Executing the init section.'
      appveyor version


# Install scripts. (runs after repo cloning)
install:
  - sh: |
      echo 'Executing the install section.'
      echo 'The current NVM version is $(nvm --version)'
      nvm ls
      nvm install $(cat .nvmrc)
      npm --quiet install

before_build:
  - sh: echo 'Running scripts before build.'

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - sh: "echo hello"
#   - node --version
#   - npm --version
  # run tests
#   - npm test

# Don't actually build.
build: off
